//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AccountType { get; set; }
        public int Balance { get; set; }
    }
}
